version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: sentinel_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ai_livestock_sentinel

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sentinel_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB_NAME=ai_livestock_sentinel
      - JWT_SECRET=sih_2026_sentinel_super_secret_key_90123
      - CORS_ORIGINS=*
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sentinel_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
